### ISSUE TITLE
feature request: allow CLIPR to be available to everyone

### ISSUE THREAD

**Issue by diegovinas** [cloudfoundry-incubator/cli-plugin-repo#134]
When I push the CLIPR app to my Cloud Foundry installation and add it as a plugin repository with "cf add-plugin-repo", only I can see the repo and install the plugins defined in it, other users cannot (even though they can access to the CLIPR app URL itself)

Would it be possible to make CLIPR available to anyone in a CF installation to make the plugins globally accessible to everyone with access to that CF?

**Comment by nickwei84** [comment]
Hi @diegovinas. The plugin information is stored locally in your home directory by default (`$HOME/.cf/plugin/`). Could it be that the other users are not sharing the same home directory as you? There is an environment variable `CF_PLUGIN_HOME` that allows you to set the home directory used for plugins. You can share your plugin home directory with others this way.

**Comment by diegovinas** [comment]
Hi @nickwei84, I was under the impression that when the custom CLIPR owner pushes it to CF and runs "cf add-plugin-repo", the repo is available to every CLI user accessing from their own computers. I guess every user needs to run "cf add-plugin-repo" to be able to "see/install' to the plugins in the custom CLIPR.

At least that worked for me.

However,  typically CLI users may use their own computer to run cf commands (not a shared computer) so ideally  "adding" the repo should not have to be done by every user. Just a suggestion.

**Comment by nickwei84** [comment]
@diegovinas You are correct that each user on a different machine/user profile will, by default, need to add the plugin repository. You have a good idea, however sharing plugin repos becomes a much more difficult feat when doing so amongst users with different levels of authorization, as well as managing permissions. Currently the cloud controller API does not support sharing plugin repos amongst multiple users. Please feel free to submit a feature request to the cloud controller API here: https://github.com/cloudfoundry/cloud_controller_ng.

**Comment by diegovinas** [comment]
Since there is a workaround (each user executing "cf add-plugin-repo" in order to see/install a plugin in that repo) and the feature needs to be implemented in the API first, I'm closing this item. Thanks you  @nickwei84 for the clarification.
