### ISSUE TITLE
Best way to debug plugin

### ISSUE THREAD

**Issue by sysintelligent** [cloudfoundry-incubator/cli-plugin-repo#147]
Hey I'm wondering what's the best way to debug plugin? I can debug GO locally but have no idea to do that with plugin? Cloud you shed some light on this?

Thanks
David

**Comment by pivotal-stuart-pollock** [comment]
I have added a response in our public Slack channel.  https://cloudfoundry.slack.com/archives/C032824SM/p1500313993174976
