### ISSUE TITLE
Windows binary signing instructions needed

### ISSUE THREAD

**Issue by mogul** [cloudfoundry-incubator/cli-plugin-repo#165]
We’re finding government users are unable to use unsigned Windows binaries on locked-down laptops. When a binary is signed, it’s easier for admins in similarly locked-down environments to whitelist either by individual signature or by publisher. 

The CF CLI itself is signed, but the plugins generally aren’t. I'd like to see instructions for signing Windows binaries added to [the section of the docs about cross-compiling binaries](https://github.com/cloudfoundry-incubator/cli-plugin-repo#cross-compile-to-the-3-different-operating-systems). 

For reference, [here's how the CLI does it](https://github.com/cloudfoundry/cli/blob/master/ci/cli-release/tasks/sign-windows-binaries.yml#L28-L47). Reference [this Slack discussion](https://cloudfoundry.slack.com/archives/C032824SM/p1504822486000185).

**Comment by dkoper** [comment]
Hi @mogul 

We added instructions here: https://github.com/cloudfoundry-incubator/cli-plugin-repo#sign-windows-binaries

Hope that helps!
Regards,
Dies Koper
CF CLI PM

**Comment by mogul** [comment]
Huzzah, thanks for the rapid turnaround!
