### ISSUE TITLE
Travis failure: Plugin 'Copy Env' has an invalid checksum for platform 'osx'

### ISSUE THREAD

**Issue by glyn** [cloudfoundry-incubator/cli-plugin-repo#179]
This fails on master https://travis-ci.org/cloudfoundry-incubator/cli-plugin-repo/builds/286081920.

I presume that the binary has been modified since the checksum was computed.

**Comment by glyn** [comment]
@jthomas I raised this to ensure the problem is tracked.

**Comment by csterwa** [comment]
@dkoper I believe that this issue is blocking the PR that @glyn created.

https://github.com/cloudfoundry-incubator/cli-plugin-repo/pull/178

**Comment by dkoper** [comment]
I have removed the updated plugin binary with the invalid checksum - tests were passing after that change.
