### ISSUE TITLE
allow multiple versions of a plugin to coexist in the repo

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry-incubator/cli-plugin-repo#31]
we may need to allow the user to to able to select and install different versions of the plugin as the user may interact with different cloud environments, and sometimes we can not guarentee the backward compatibility.  This can be done by having multiple plugin entries for different versions in repo-index.yml.  But a better way might be having one entry for the  plugin, and multiple sub-entries for differetn versions

We can force only one version can be installed  to avoid command conflict.  

To enable this, there will be corresponding changes on the cf cli side too. E.g 

cf install-plugin PLUGIN-NAME or LOCAL-PATH/TO/PLUGIN [-r REPO_NAME] [-v VERSION]

**Comment by goehmen** [comment]
@boyang9527 Can you describe your use case more clearly please?  I'm not sure this is a good UX overall.
