### ISSUE TITLE
Can author be an array?

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry-incubator/cli-plugin-repo#4]
to support multiple developers on single plugin

**Comment by simonleung8** [comment]
HI, currently `author` has to be a string. You can provide multiple names in the field, the entire string will be displayed.

**Comment by simonleung8** [comment]
@longnguyen11288 : Hi, we have made the follow new changes in the author field.
- it is called `authors`
- supports an array of author
- each author has sub-fields: name, homepage, contact

Thanks for raising the issue and we figured an array of authors is a better way to go.

**Comment by longnguyen11288** [comment]
Thanks!
