### ISSUE TITLE
plugins.cloudfoundry.org shouldn't be available via plain http

### ISSUE THREAD

**Issue by davidillsley** [cloudfoundry-incubator/cli-plugin-repo#68]
As I understand the plugin install process (and I'm pretty new to it), the fact that plugins.cloudfoundry.org is available via plain HTTP (and that the CLI [defaults to the non-HTTPS version](https://github.com/cloudfoundry/cli/blob/master/cf/configuration/coreconfig/config_repository.go#L43)) introduces a vulnerability that an attacker can cause the cli to install a malicious binary when a user attempts to install a plugin.

Assuming the above is true, in order to protect users, the repo shouldn't be available via plain HTTP when run on the internet (having it as an option for intranet deployments may be reasonable).

**Comment by XenoPhex** [comment]
Thanks for paying attention about the security concerns of plugins repo. We are already redirect all http traffic to https and have updated most of the links on our side of things to use the https.

We also added validations in our repo-index.yml to require all download links to be done over SSL, otherwise our tests will fail, preventing people from adding non-secure download links.

**Comment by dkoper** [comment]
@davidillsley and apologies for the late feedback.
We acted on your issue report immediately as you may have noticed, but failed to update this issue. (We get so few issue reports on this repo I haven't been in the habit of regularly revisiting it).

If you find any other security issues, do please contact us directly first or follow the following process to give us a chance to evaluate and address it before you share it with the rest of the world?
https://github.com/cloudfoundry-community/cf-docs-contrib/wiki/Reporting-Security-Vulnerabilities

Cheers,
Dies Koper
CF CLI PM

**Comment by davidillsley** [comment]
Will do. I did look for something like that, but couldn't find it. Would be good if there was a link from cloudfoundry.org somewhere, so that a google for 'site:cloudfoundry.org security' did the right thing.
